name: csev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - geopandas
  - rasterio
  - numpy
  - pandas
  - matplotlib
  - pip
  - pip:
    # no additional pip-only dependencies
